kind: NginxIngress
apiVersion: charts.nginx.org/v1alpha1
metadata:
  name: my-nginx-ingress-controller
  namespace: my-nginx-ingress
spec:
  type: deployment
  nginxPlus: false
  image:
    repository: nginx/nginx-ingress
    tag: 2.1.1-ubi
    pullPolicy: Always
  replicas: 1
  serviceType: NodePort
